### ISSUE TITLE
Choice doesn't support string

### ISSUE THREAD

**Issue by vighnesh153** [rv-npm/vighnesh153-random#4]
The `Random.choice()` function doesn't accept `string` as a parameter. Request to add feature/support for it.

**Comment by tavisca-vraut** [comment]
The simplest way to solve this would be to check if the argument passed is `string`, then convert it into an `array` of characters and proceed the same way. But this would be inefficient as we are converting the `string` to an `array` of characters whose time complexity is `O(size(string))`. So, maybe a better way is to remove the strict `isArray` check and also add the `isString` check along with it.
